spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory-route
              uri: lb://inventory-service
#              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/inventory/**

            - id: order-route
              uri: lb://order-service
              predicates:
                - Path=/api/v1/order/**

            - id: item-route
              uri: lb://item-service
              predicates:
                - Path=/api/v1/item/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/